name: datapack-linter
author: chen
description: Processing to lint datapack
runs:
  using: node12
  main: 'dist/index.js'
branding:
  icon: box
  color: green
inputs:
  outputDefine:
    description: 'Shows the definition that the resource path passed in the argument can be referenced. Also, if "public" is specified as an argument, the declaration that can be referenced from the whole is displayed. This argument can describe multiple resource paths by using line breaks.'
    required: false