name: datapack-linter
author: chen
description: Processing to lint datapack
runs:
  using: node12
  main: 'dist/index.js'
branding:
  icon: box
  color: green
inputs:
  DEBUG:
    description: 'Setting this argument to "true" will force the test to pass.'
    required: false