name: datapack-linter
author: chen
description: Processing to lint datapack
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git clone https://github.com/ChenCMD/datapack-linter.git
        echo "::add-matcher::datapack-linter/matcher.json"
        cd datapack-linter
        npm i
        npm run lint-dp
branding:
  icon: box
  color: green
