name: datapack-linter
author: chen
description: Processing to lint datapack
runs:
  using: node16
  main: 'index.js'
branding:
  icon: box
  color: green
inputs:
  lintDirectory:
    description: 'Lint base directory.'
    required: false
    default: '.'
  configPath:
    description: 'Path of a configuration file.'
    required: false
    default: '.vscode/settings.json'
  forcePass:
    description: 'If set to "true", the check will not fail if any files fail.'
    required: false
    default: 'false'
  muteSuccessResult:
    description: 'If set to "true", the result of successfully checked files is not output.'
    required: false
    default: 'false'
  ignoreLintPathPattern:
    description: 'Do not check for files that match the entered globPattern.'
    required: false
    default: ''
  alwaysCheckAllFile:
    description: 'If set to "true", it will always check all files without using the cache.'
    required: false
    default: 'false'