name: datapack-linter
author: chen
description: Processing to lint datapack
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npm i
        node run lint-dp
branding:
  icon: box
  color: green
