name: lint-datapack
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: test
        uses: ChenCMD/datapack-linter@dev
        with:
          DEBUG: 'true'
          outputDefine: 'public'