name: lint-datapack
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
      - name: clone test datapack
        run: |
          git clone -b test-datapack https://github.com/ChenCMD/datapack-linter.git datapack

      - name: test
        working-directory: test
        uses: ChenCMD/datapack-linter@dev