name: Test run and Deploy to dist branch
on:
  push:
    branches-ignore:
      - dist
  pull_request:
  workflow_dispatch:
jobs:
  test-run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-deps-${{ hashFiles('./yarn.lock') }}

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.ivy2/local/org.scalablytyped
            ./target/scala-*/scalajs-bundler/node_modules
          key: ${{ runner.os }}-sbt-deps-${{ hashFiles('./build.sbt') }}

      - name: Install Node dependencies
        run: yarn install

      - name: Build for production
        run: yarn build

      - name: Test run
        run: yarn test

      - name: Pre deploy
        if: ${{ github.ref == 'ref/heads/main' }}
        run: cp action.yml README.md dist/.

      - name: Deploy to dist
        if: ${{ github.ref == 'ref/heads/main' }}
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dist
          directory: dist
          message: Compiled from ${{ github.SHA }}