name: Test run and Deploy to dist branch
on:
  push:
    branches-ignore:
      - dist
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout dist branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v3
        with:
          ref: dist
          path: ./dist

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-deps-${{ hashFiles('./yarn.lock') }}

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.ivy2/local/org.scalablytyped
            ./target/scala-*/scalajs-bundler/node_modules
          key: ${{ runner.os }}-sbt-deps-${{ hashFiles('./build.sbt') }}

      - name: Build for production
        run: sbt fullOptJS/webpack
        env:
          SBT_OPTS: "-Xmx4G -XX:+UseG1GC"

      - name: Move build files
        run: |
          mv dist/datapack-linter-opt-bundle.js dist/index.js
          mv target/scala-3.4.0/scalajs-bundler/main/datapack-linter-opt.js.map dist/index.js.map
          mv dist/datapack-linter-opt-bundle.js.LICENSE.txt dist/index.js.LICENSE.txt

      - name: Export environments
        uses: peaceiris/actions-export-envs@v1.1.0
        id: envs

      - name: Run
        run: yarn test-gh-run
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ steps.envs.outputs.ACTIONS_RUNTIME_TOKEN }}
          ACTIONS_CACHE_URL: ${{ steps.envs.outputs.ACTIONS_CACHE_URL }}
          INPUT_GITHUB_TOKEN: ${{ github.token }}
          INPUT_IGNORELINTPATHPATTERN: test:ignore/**
          INPUT_FORCEPASS: true

      - name: Pre deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cp action.yml LICENSE README.md .gitignore dist

      - name: Deploy to dist
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dist
          directory: ./dist
          empty: true
          message: Compiled from ${{ github.SHA }}
